import { useEffect, useState } from "react";
import { BriefcaseBusiness, Plus, Save, Trash2, RefreshCw } from "lucide-react";
import { loadCloudDocumentTypes, loadCloudJobs, saveCloudJob, deleteCloudJob, type CloudJob } from "../cloud";

export default function JobsPage({ templates, onOpenTemplate }: { templates:{id:string;name:string;cloudId?:string}[]; onOpenTemplate:(id:string)=>void }) {
 const [jobs,setJobs]=useState<CloudJob[]>([]),[types,setTypes]=useState<any[]>([]),[selected,setSelected]=useState<CloudJob|null>(null);
 const [name,setName]=useState(""),[code,setCode]=useState(""),[description,setDescription]=useState(""),[typeId,setTypeId]=useState(""),[templateId,setTemplateId]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const load=async()=>{setBusy(true);try{const [j,t]=await Promise.all([loadCloudJobs(),loadCloudDocumentTypes()]);setJobs(j);setTypes(t);if(!selected&&j[0]) edit(j[0])}catch(e){setMessage(e instanceof Error?e.message:"Chargement impossible")}finally{setBusy(false)}};
 useEffect(()=>{load()},[]);
 const edit=(j:CloudJob)=>{setSelected(j);setName(j.name);setCode(j.code);setDescription(j.description??"");setTypeId(j.document_type_id??"");setTemplateId(j.template_id??"")};
 const fresh=()=>{setSelected(null);setName("");setCode("");setDescription("");setTypeId("");setTemplateId("");setMessage("")};
 const save=async()=>{if(!name.trim()||!code.trim()){setMessage("Nom et code sont obligatoires.");return}setBusy(true);try{const j=await saveCloudJob({id:selected?.id,name,code,description,document_type_id:typeId||null,template_id:templateId||null});setJobs(v=>[j,...v.filter(x=>x.id!==j.id)]);edit(j);setMessage("Job enregistré.");}catch(e){setMessage(e instanceof Error?e.message:"Enregistrement impossible")}finally{setBusy(false)}};
 const remove=async()=>{if(!selected||!confirm("Supprimer ce job ?"))return;setBusy(true);try{await deleteCloudJob(selected.id);setJobs(v=>v.filter(x=>x.id!==selected.id));fresh();setMessage("Job supprimé.")}catch(e){setMessage(e instanceof Error?e.message:"Suppression impossible")}finally{setBusy(false)}};
 return <div className="page"><div className="heading"><div><h2>Jobs</h2><p>Un Job définit le type de document, le modèle et les données attendues.</p></div><div className="actions"><button onClick={load} disabled={busy}><RefreshCw size={16}/> Actualiser</button><button className="dark" onClick={fresh}><Plus size={16}/> Nouveau Job</button></div></div>
 <div className="jobs-layout"><section className="mapping-card"><div className="section-title"><h3>Mes Jobs</h3><span>{jobs.length}</span></div>{jobs.map(j=><button key={j.id} className={"job-row "+(selected?.id===j.id?"job-selected":"")} onClick={()=>edit(j)}><BriefcaseBusiness size={16}/><span><b>{j.name}</b><small>{j.code}</small></span></button>)}{!jobs.length&&<p>Aucun Job cloud. Connectez-vous à Supabase puis créez votre premier Job.</p>}</section>
 <section className="mapping-card"><div className="section-title"><h3>{selected?"Modifier le Job":"Créer un Job"}</h3>{selected&&<button onClick={remove} disabled={busy}><Trash2 size={15}/> Supprimer</button>}</div>
 <div className="job-form"><label>Nom<input value={name} onChange={e=>setName(e.target.value)} placeholder="Formation OM 2026"/></label><label>Code<input value={code} onChange={e=>setCode(e.target.value)} placeholder="FORMATION_OM_2026"/></label><label>Type de document<select value={typeId} onChange={e=>setTypeId(e.target.value)}><option value="">— Aucun —</option>{types.map(t=><option key={t.id} value={t.id}>{t.name} ({t.code})</option>)}</select></label><label>Modèle<select value={templateId} onChange={e=>setTemplateId(e.target.value)}><option value="">— Aucun —</option>{templates.map(t=><option key={t.cloudId??t.id} value={t.cloudId??t.id}>{t.name}</option>)}</select></label><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="Description du traitement de documents"/></label></div>
 <div className="actions"><button className="dark" onClick={save} disabled={busy}><Save size={16}/> {busy?"Enregistrement…":"Enregistrer le Job"}</button>{message&&<span>{message}</span>}</div></section></div></div>
}
